language: node_js
cache:
  directories:
  - node_modules
node_js:
    - "9"
    - "8"
    - "6"
script:
  - npm test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on: 
    tags: true          

# jobs:
#   include:
#     - stage: npm release
#       node_js: "8"
#       script: echo "Deploying to npm ..."
#       deploy:
#         provider: npm
#         email: $NPM_EMAIL
#         api_key: $NPM_API_KEY
#         on: 
#           tags: true          